### ISSUE TITLE
this.physics.startSystem Error

### ISSUE THREAD

**Issue by maxinteger** [RichardOtvos/ShuriCat#1]
I got this error after start:
`Uncaught TypeError: Cannot read property 'startSystem' of null`
from this line: 
`this.physics.startSystem(Phaser.Physics.ARCADE);`

**Comment by RichardOtvos** [comment]
Fixed with https://github.com/RichardOtvos/ShuriCat/commit/73e4a81d7620559d8ab23975345d395b36e1ca36
